FROM python:3.9

EXPOSE 8080
WORKDIR /app

COPY . ./

RUN pip install -r requirements.txt
RUN pip install google-cloud-aiplatform

ENTRYPOINT ["streamlit", "run", "chef.py", "--server.port=8080", "--server.address=0.0.0.0"]